# fly.toml app configuration file generated for kubernetes-backend-autumn-pond-3037 on 2024-01-11T22:44:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kubernetes-backend-autumn-pond-3037"
primary_region = "lhr"

[build]
dockerfile = "Dockerfile"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024